apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  NEXT_PUBLIC_API_URL: "http://todo-backend:7860"
  DATABASE_URL: "DATABASE_URL"
  PYTHONPATH: "/app/src"
  JWT_SECRET: "JWT_SECRET"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "10080"
  BCRYPT_ROUNDS: "12"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "development"
  GOOGLE_API_KEY: "GOOGLE_API_KEY"